version: '3'

services:

  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    build: .
    depends_on:
      db:
        condition: service_healthy
    command: python manage.py migrate

  app:
    build: .
    tty: true
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    depends_on:
      migrations:
        condition: service_completed_successfully
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pg_data: