# Generated by Django 5.0.1 on 2024-01-24 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('supplier_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chain.supplier')),
            ],
            options={
                'verbose_name': 'завод',
                'verbose_name_plural': 'заводы',
                'ordering': ('name',),
            },
            bases=('chain.supplier',),
        ),
        migrations.CreateModel(
            name='Entrepreneur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('status', models.CharField(blank=True, editable=False, max_length=14, null=True, verbose_name='статус')),
                ('debt_to_supplier', models.FloatField(blank=True, null=True, verbose_name='задолженность перед поставщиком')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chain.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'индивидуальный предприниматель',
                'verbose_name_plural': 'индивидуальные предприниматели',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='RetailNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('street', models.CharField(max_length=50, verbose_name='улица')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='номер дома')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('status', models.CharField(blank=True, editable=False, max_length=14, null=True, verbose_name='статус')),
                ('debt_to_supplier', models.FloatField(blank=True, null=True, verbose_name='задолженность перед поставщиком')),
                ('products', models.ManyToManyField(to='products.product', verbose_name='продукты')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chain.supplier', verbose_name='поставщик')),
            ],
            options={
                'verbose_name': 'розничная сеть',
                'verbose_name_plural': 'розничные сети',
                'ordering': ('name',),
            },
        ),
    ]
